spring:
  docker:
    compose:
      file: compose-infrastructure.yml
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  r2dbc:
    pool:
      max-size: 100
      initial-size: 1

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

#logging:
#  level:
#    org.springframework.data.r2dbc: debug
#    org.springframework.r2dbc: debug